#!/usr/bin/env node
// ============================================================================
// Gym Flow — hybrid APK bundle generator.
//
// Builds mobile/www from the repo so the ENTIRE frontend ships inside the APK
// and only /api/v1 traffic leaves the device:
//   • every page in server.js's `pages` table  -> www/<route>/index.html
//   • public/assets (js/css/img/fonts/vendor)  -> www/assets
//   • mobile/shell/index.html (launcher)       -> www/index.html
//   • www/capacitor-env.js (generated)         -> window.API_BASE_URL marker
//
// Per-page transforms (bundle only — the web-served code.html is untouched):
//   1. inject <script src="/capacitor-env.js"> before every other script
//   2. CDN -> bundled: chart.js, qrious, Material Symbols font (icons must
//      render offline; text fonts keep the Google CDN and fall back to the
//      system font when offline — cosmetic only)
//
// Deliberately NOT bundled: public/sw.js (no SW in the APK — assets are already
// local), public/models (1.9GB on-device LLM; the native side manages it).
//
// Usage:  node build-www.js            (uses API_BASE below)
//         API_BASE=https://x node build-www.js
// ============================================================================
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const WWW = path.join(__dirname, 'www');
const API_BASE = (process.env.API_BASE || 'https://thegymflow.in').replace(/\/+$/, '');

// ---- 1. Page table: parse server.js so the bundle can never drift from it.
const serverSrc = fs.readFileSync(path.join(ROOT, 'server.js'), 'utf8');
const pagesBlock = serverSrc.match(/const pages = \[([\s\S]*?)\];/);
if (!pagesBlock) throw new Error('Could not find `const pages = [...]` in server.js');
const pages = [...pagesBlock[1].matchAll(/route:\s*'([^']+)'\s*,\s*dir:\s*'([^']+)'/g)]
  .map(m => ({ route: m[1], dir: m[2] }));
if (pages.length < 30) throw new Error(`Only parsed ${pages.length} pages from server.js — format changed?`);

// ---- helpers
function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function copyDir(src, dest) { fs.cpSync(src, dest, { recursive: true }); }
function write(p, content) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}

const MSYM_LINK = 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap';

function transformPage(html) {
  return html
    // capacitor-env.js must run before api.js / netTransport.js read API_BASE_URL
    .replace(/<head([^>]*)>/i, '<head$1><script src="/capacitor-env.js"></script>')
    .replace(/https:\/\/cdn\.jsdelivr\.net\/npm\/chart\.js/g, '/assets/js/vendor/chart.umd.js')
    .replace(/https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/qrious\/[^"']+\/qrious\.min\.js/g, '/assets/js/vendor/qrious.min.js')
    .replace(/https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/cropperjs\/[^"']+\/(cropper\.min\.(?:js|css))/g, '/assets/js/vendor/$1')
    .replace(/https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/html2pdf\.js\/[^"']+\/html2pdf\.bundle\.min\.js/g, '/assets/js/vendor/html2pdf.bundle.min.js')
    .replace(MSYM_LINK, '/assets/fonts/material-symbols.css');
}

// ---- 2. clean + static payload
rmrf(WWW);
fs.mkdirSync(WWW, { recursive: true });
copyDir(path.join(ROOT, 'public', 'assets'), path.join(WWW, 'assets'));
fs.copyFileSync(path.join(ROOT, 'public', 'manifest.webmanifest'), path.join(WWW, 'manifest.webmanifest'));
fs.copyFileSync(path.join(__dirname, 'assets', 'logo.png'), path.join(WWW, 'logo.png'));

// ---- 3. generated env (single source of truth for the backend origin) + the
// two-way router that reconciles clean routes with Capacitor's SPA fallback:
// WebViewLocalServer serves the ROOT index.html for EVERY extensionless path
// (html5mode, WebViewLocalServer.java:399), so:
//   root doc loaded at /members     -> hop to the real /members/index.html
//   real page /members/index.html   -> history.replaceState back to /members so
//   every location.pathname consumer (utils.js publicPaths, nav highlighting,
//   the 401 login gates) sees the same clean routes as the web app.
// This file is injected as the FIRST script of every page, so the URL is
// already clean by the time any other script reads it.
write(path.join(WWW, 'capacitor-env.js'),
  `// GENERATED by mobile/build-www.js — do not edit.
window.__NATIVE_SHELL__ = true;
window.API_BASE_URL = '${API_BASE}';
(function () {
  var p = location.pathname.replace(/\\/+$/, '');
  if (p.slice(-11) === '/index.html') {
    var clean = p.slice(0, -11) || '/';
    try { history.replaceState(history.state, '', clean + location.search + location.hash); } catch (e) {}
  } else if (p && p.indexOf('.') === -1) {
    // Extensionless path served the root launcher: hand off to the bundled page.
    window.__ROUTED__ = true;
    location.replace(p + '/index.html' + location.search + location.hash);
  }
})();
`);

// ---- 4. launcher (+ its external boot script — external because the shell CSP
// has no 'unsafe-inline'; an inline script is refused and the splash hangs)
const shell = fs.readFileSync(path.join(__dirname, 'shell', 'index.html'), 'utf8');
write(path.join(WWW, 'index.html'), shell.replace(/__API_ORIGIN__/g, API_BASE));
fs.copyFileSync(path.join(__dirname, 'shell', 'launcher.js'), path.join(WWW, 'launcher.js'));

// ---- 5. every app page -> www/<route>/index.html
for (const p of pages) {
  const src = path.join(ROOT, p.dir, 'code.html');
  write(path.join(WWW, p.route.replace(/^\//, ''), 'index.html'), transformPage(fs.readFileSync(src, 'utf8')));
}

// print view: the one screen-folder file the UI opens directly (server.js C3 note)
const printSrc = path.join(ROOT, 'daily_closing_report_kinetic_enterprise', 'print.html');
write(path.join(WWW, 'daily_closing_report_kinetic_enterprise', 'print.html'),
  transformPage(fs.readFileSync(printSrc, 'utf8')));

console.log(`Built www: ${pages.length} pages + launcher, API_BASE=${API_BASE}`);
