// ============================================================================
// Gym Flow — desktop (Electron) bundled-offline shell.
//
// Mirrors the Android hybrid APK: the ENTIRE frontend ships inside the app
// (reused from mobile/www, generated by mobile/build-www.js) and only /api/v1
// traffic leaves the machine, to the Render backend baked into the bundle's
// capacitor-env.js. We serve www over a loopback HTTP origin (NOT file://) for
// two reasons the app depends on:
//   1. absolute asset paths (/assets, /capacitor-env.js) resolve against a root
//   2. 127.0.0.1 is a Chromium "secure context", so the cross-site
//      SameSite=None; Secure session cookies to Render are sent/stored exactly
//      as they are in the Android WebView (which serves over https://localhost).
// A custom app:// protocol would break (2), so a tiny loopback server it is.
// ============================================================================
'use strict';

const { app, BrowserWindow, shell } = require('electron');
const http = require('http');
const fs = require('fs');
const path = require('path');

// Bundled frontend: packaged → resources/www (extraResources); dev → mobile/www.
const WWW = app.isPackaged
  ? path.join(process.resourcesPath, 'www')
  : path.join(__dirname, '..', 'mobile', 'www');

const MIME = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.webmanifest': 'application/manifest+json', '.png': 'image/png', '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg', '.gif': 'image/gif', '.svg': 'image/svg+xml', '.ico': 'image/x-icon',
  '.webp': 'image/webp', '.woff': 'font/woff', '.woff2': 'font/woff2', '.ttf': 'font/ttf',
  '.map': 'application/json', '.wasm': 'application/wasm'
};

// Resolve a request path to a file inside WWW without escaping it. Mirrors the
// Capacitor WebViewLocalServer: extensionless routes fall back to <route>/index.html.
function resolveFile(urlPath) {
  let p = decodeURIComponent((urlPath.split('?')[0] || '/').split('#')[0]);
  p = path.posix.normalize(p);
  if (p === '/' || p === '.') return path.join(WWW, 'index.html');
  const rel = p.replace(/^\/+/, '');
  const abs = path.join(WWW, rel);
  // Containment guard — never serve outside the bundle.
  if (!abs.startsWith(WWW)) return null;
  if (fs.existsSync(abs) && fs.statSync(abs).isFile()) return abs;
  if (!path.extname(abs)) {
    const idx = path.join(abs, 'index.html');
    if (fs.existsSync(idx)) return idx;
  }
  return null;
}

function startServer() {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      const file = resolveFile(req.url || '/');
      if (!file) { res.writeHead(404); res.end('Not found'); return; }
      fs.readFile(file, (err, buf) => {
        if (err) { res.writeHead(500); res.end('Read error'); return; }
        res.writeHead(200, { 'Content-Type': MIME[path.extname(file)] || 'application/octet-stream' });
        res.end(buf);
      });
    });
    // Ephemeral port on loopback only.
    server.listen(0, '127.0.0.1', () => resolve(server.address().port));
    server.on('error', reject);
  });
}

// The API origin baked into the bundle (mobile/build-www.js writes it into
// capacitor-env.js). Needed to scope the Origin rewrite below.
function bundledApiOrigin() {
  try {
    const src = fs.readFileSync(path.join(WWW, 'capacitor-env.js'), 'utf8');
    const m = src.match(/API_BASE_URL\s*=\s*'([^']+)'/);
    return m ? m[1] : null;
  } catch (e) { return null; }
}

// The whole backend treats `Origin: https://localhost` as "the bundled app":
// CORS allow-list, CSRF allow-list AND SameSite=None session cookies are all
// keyed on it (server.js CAPACITOR_ORIGINS + lib/identity cookieOptionsFor).
// Our renderer's real origin is http://127.0.0.1:<random port>, which the
// server rightly rejects. Present the Capacitor origin on API requests, and
// rewrite the CORS response header back to the real origin so Chromium's own
// check passes. Desktop then rides the exact same server path as the APK.
function wireApiOrigin(session, port) {
  const api = bundledApiOrigin();
  if (!api) return;
  const filter = { urls: [api + '/*'] };
  session.webRequest.onBeforeSendHeaders(filter, (details, cb) => {
    details.requestHeaders['Origin'] = 'https://localhost';
    cb({ requestHeaders: details.requestHeaders });
  });
  session.webRequest.onHeadersReceived(filter, (details, cb) => {
    const headers = details.responseHeaders || {};
    for (const k of Object.keys(headers)) {
      if (/^access-control-allow-(origin|credentials)$/i.test(k)) delete headers[k];
    }
    headers['Access-Control-Allow-Origin'] = [`http://127.0.0.1:${port}`];
    headers['Access-Control-Allow-Credentials'] = ['true'];
    cb({ responseHeaders: headers });
  });
}

let mainWindow = null;

async function createWindow() {
  const port = await startServer();

  mainWindow = new BrowserWindow({
    width: 1280, height: 820, minWidth: 380, minHeight: 640,
    backgroundColor: '#0B1120',
    title: 'Gym Flow',
    show: false,
    webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true }
  });

  // Razorpay checkout / Google OAuth / external links open in the real browser,
  // not a frameless child window that can't be trusted or closed cleanly.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:/i.test(url)) { shell.openExternal(url); }
    return { action: 'deny' };
  });

  wireApiOrigin(mainWindow.webContents.session, port);
  mainWindow.once('ready-to-show', () => mainWindow.show());
  mainWindow.loadURL(`http://127.0.0.1:${port}/`);
}

// Single-instance: focus the existing window instead of opening a second copy.
if (!app.requestSingleInstanceLock()) {
  app.quit();
} else {
  app.on('second-instance', () => {
    if (mainWindow) { if (mainWindow.isMinimized()) mainWindow.restore(); mainWindow.focus(); }
  });
  app.whenReady().then(createWindow);
  app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
  app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
}
